// Curriculum metadata — the single source of truth for course/lesson structure.
// Imported by prisma/seed.ts (DB seeding) and scripts/generate-static-content.ts
// (build-time public/curriculum.json). Keep titles/order in sync with the
// markdown under server/lessons and server/algorithms.

export const courses = [
  {
    key: 'python',
    title: 'Python',
    description: 'New to programming? We highly recommend Python',
    sortOrder: 1,
  },
  {
    key: 'c',
    title: 'C',
    description: 'Low-level programming, pointers, memory, and OS concepts',
    sortOrder: 2,
  },
  { key: 'java', title: 'Java', description: 'Object Oriented Programming', sortOrder: 3 },
  {
    key: 'linux',
    title: 'Linux',
    description: 'Master the terminal — files, navigation, and shell commands',
    sortOrder: 4,
  },
  {
    key: 'algo-python',
    title: 'Python Algorithms',
    description: 'Classic algorithms with strings, lists, loops, and dictionaries',
    sortOrder: 5,
  },
  {
    key: 'algo-java',
    title: 'Java Algorithms',
    description: 'OOP-focused challenges — classes, objects, inheritance, and collections',
    sortOrder: 6,
  },
  {
    key: 'algo-c',
    title: 'C Algorithms',
    description: 'Low-level challenges with arrays, pointers, structs, and memory',
    sortOrder: 7,
  },
  {
    key: 'kotlin',
    title: 'Kotlin',
    description: 'Modern JVM language — concise, safe, and interoperable',
    sortOrder: 8,
  },
];

export const lessons = [
  { courseKey: 'python', slug: 'print', title: 'Print', sortOrder: 1, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'variables-str',
    title: 'Variables (Strings)',
    sortOrder: 2,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'variables-int',
    title: 'Variables (Integers)',
    sortOrder: 3,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'print-f',
    title: 'Print F-strings',
    sortOrder: 4,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-variables',
    title: 'Recap: Player Card',
    sortOrder: 5,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'comment', title: 'Comments', sortOrder: 6, hasCodeFile: true },
  { courseKey: 'python', slug: 'if-else', title: 'If/Else', sortOrder: 7, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'if-elif-else',
    title: 'If/Elif/Else',
    sortOrder: 8,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-conditionals',
    title: 'Recap: Ticket Calculator',
    sortOrder: 9,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'for', title: 'For Loops', sortOrder: 10, hasCodeFile: true },
  { courseKey: 'python', slug: 'while', title: 'While Loops', sortOrder: 11, hasCodeFile: true },
  { courseKey: 'python', slug: 'functions', title: 'Functions', sortOrder: 12, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'recap-loops',
    title: 'Recap: Number Hints',
    sortOrder: 13,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'input', title: 'Input', sortOrder: 14, hasCodeFile: true },
  { courseKey: 'python', slug: 'operators', title: 'Operators', sortOrder: 15, hasCodeFile: true },
  { courseKey: 'python', slug: 'booleans', title: 'Booleans', sortOrder: 16, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'recap-logic',
    title: 'Recap: Username Validator',
    sortOrder: 17,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'strings-methods',
    title: 'String Methods',
    sortOrder: 18,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'lists', title: 'Lists', sortOrder: 19, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'lists-for',
    title: 'Looping over Lists',
    sortOrder: 20,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'break-continue',
    title: 'Break and Continue',
    sortOrder: 21,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-collections',
    title: 'Recap: Shopping List',
    sortOrder: 22,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'return', title: 'Return Values', sortOrder: 23, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'dictionaries',
    title: 'Dictionaries',
    sortOrder: 24,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'dictionaries-loop',
    title: 'Looping over Dictionaries',
    sortOrder: 25,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-dicts',
    title: 'Recap: Grade Report',
    sortOrder: 26,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'tuples', title: 'Tuples', sortOrder: 27, hasCodeFile: true },
  { courseKey: 'python', slug: 'sets', title: 'Sets', sortOrder: 28, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'nested-loops',
    title: 'Nested Loops',
    sortOrder: 29,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'list-comprehension',
    title: 'List Comprehension',
    sortOrder: 30,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-data-structures',
    title: 'Recap: Class Analyzer',
    sortOrder: 31,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'scope', title: 'Scope', sortOrder: 32, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'default-params',
    title: 'Default Parameters',
    sortOrder: 33,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'multiple-return',
    title: 'Multiple Return Values',
    sortOrder: 34,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'try-except',
    title: 'Try / Except',
    sortOrder: 35,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-functions-adv',
    title: 'Recap: Safe Math Toolkit',
    sortOrder: 36,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'builtin-functions',
    title: 'Built-in Functions',
    sortOrder: 37,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'problem-decomposition',
    title: 'Problem Decomposition',
    sortOrder: 38,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'pattern-counter',
    title: 'Pattern: Counter',
    sortOrder: 39,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'pattern-accumulator',
    title: 'Pattern: Accumulator',
    sortOrder: 40,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'pattern-flag',
    title: 'Pattern: Flag',
    sortOrder: 41,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-patterns',
    title: 'Recap: Text Analyzer',
    sortOrder: 42,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'linear-search',
    title: 'Linear Search',
    sortOrder: 43,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'frequency-dict',
    title: 'Frequency Dictionary',
    sortOrder: 44,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'bubble-sort',
    title: 'Bubble Sort',
    sortOrder: 45,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'selection-sort',
    title: 'Selection Sort',
    sortOrder: 46,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-algorithms',
    title: 'Recap: Leaderboard',
    sortOrder: 47,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'string-reverse',
    title: 'Reverse a String',
    sortOrder: 48,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'palindrome',
    title: 'Palindrome',
    sortOrder: 49,
    hasCodeFile: true,
  },
  { courseKey: 'python', slug: 'anagram', title: 'Anagram', sortOrder: 50, hasCodeFile: true },
  {
    courseKey: 'python',
    slug: 'list-filter-transform',
    title: 'Filter and Transform',
    sortOrder: 51,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'two-pointers',
    title: 'Two Pointers',
    sortOrder: 52,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-problem-solving',
    title: 'Recap: Word Game Toolkit',
    sortOrder: 53,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recursion-intro',
    title: 'Recursion',
    sortOrder: 54,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recursion-practice',
    title: 'Recursion Practice',
    sortOrder: 55,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'matrix-basics',
    title: 'Matrices (2D Lists)',
    sortOrder: 56,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'binary-search',
    title: 'Binary Search',
    sortOrder: 57,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'recap-recursion',
    title: 'Recap: Dungeon Explorer',
    sortOrder: 58,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'project-guessing-game',
    title: 'Project: Guessing Game',
    sortOrder: 59,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'project-quiz',
    title: 'Project: Quiz Game',
    sortOrder: 60,
    hasCodeFile: true,
  },
  {
    courseKey: 'python',
    slug: 'project-todo',
    title: 'Project: To-Do List',
    sortOrder: 61,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'print', title: 'Print', sortOrder: 1, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'variables-int',
    title: 'Variables (Integers)',
    sortOrder: 2,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'variables-float',
    title: 'Variables (Floats)',
    sortOrder: 3,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'comment', title: 'Comments', sortOrder: 4, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'recap-variables',
    title: 'Recap: Road Trip Calculator',
    sortOrder: 5,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'if-else', title: 'If/Else', sortOrder: 6, hasCodeFile: true },
  { courseKey: 'c', slug: 'if-else-if', title: 'If/Else If/Else', sortOrder: 7, hasCodeFile: true },
  { courseKey: 'c', slug: 'for', title: 'For Loops', sortOrder: 8, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'recap-control-flow',
    title: 'Recap: FizzBuzz',
    sortOrder: 9,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'while', title: 'While Loops', sortOrder: 10, hasCodeFile: true },
  { courseKey: 'c', slug: 'functions', title: 'Functions', sortOrder: 11, hasCodeFile: true },
  { courseKey: 'c', slug: 'input', title: 'Input', sortOrder: 12, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'recap-functions',
    title: 'Recap: Mini Calculator',
    sortOrder: 13,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'operators', title: 'Operators', sortOrder: 14, hasCodeFile: true },
  { courseKey: 'c', slug: 'booleans', title: 'Booleans', sortOrder: 15, hasCodeFile: true },
  { courseKey: 'c', slug: 'strings', title: 'Strings', sortOrder: 16, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'recap-logic',
    title: 'Recap: Password Validator',
    sortOrder: 17,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'arrays', title: 'Arrays', sortOrder: 18, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'arrays-for',
    title: 'Looping over Arrays',
    sortOrder: 19,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'break-continue',
    title: 'Break and Continue',
    sortOrder: 20,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'recap-arrays',
    title: 'Recap: Grade Analyzer',
    sortOrder: 21,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'nested-loops', title: 'Nested Loops', sortOrder: 22, hasCodeFile: true },
  { courseKey: 'c', slug: 'pointers', title: 'Pointers', sortOrder: 23, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'pointers-functions',
    title: 'Pointers and Functions',
    sortOrder: 24,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'recap-pointers',
    title: 'Recap: Matrix Stats',
    sortOrder: 25,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'pointers-arrays',
    title: 'Pointers and Arrays',
    sortOrder: 26,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'strings-functions',
    title: 'String Functions',
    sortOrder: 27,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'structs', title: 'Structs', sortOrder: 28, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'structs-pointers',
    title: 'Structs and Pointers',
    sortOrder: 29,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'recap-structs',
    title: 'Recap: Contact Book',
    sortOrder: 30,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'malloc-free',
    title: 'Dynamic Memory',
    sortOrder: 31,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'enums', title: 'Enums', sortOrder: 32, hasCodeFile: true },
  { courseKey: 'c', slug: 'typedef', title: 'Typedef', sortOrder: 33, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'recap-memory',
    title: 'Recap: Task Manager',
    sortOrder: 34,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'preprocessor', title: 'Preprocessor', sortOrder: 35, hasCodeFile: true },
  { courseKey: 'c', slug: 'file-io', title: 'File I/O', sortOrder: 36, hasCodeFile: true },
  { courseKey: 'c', slug: 'bitwise', title: 'Bitwise Operators', sortOrder: 37, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'recap-advanced',
    title: 'Recap: Config & Permissions',
    sortOrder: 38,
    hasCodeFile: true,
  },
  { courseKey: 'c', slug: 'os-intro', title: 'OS: Processes', sortOrder: 39, hasCodeFile: true },
  { courseKey: 'c', slug: 'os-fork', title: 'OS: Fork', sortOrder: 40, hasCodeFile: true },
  { courseKey: 'c', slug: 'os-pipes', title: 'OS: Pipes', sortOrder: 41, hasCodeFile: true },
  { courseKey: 'c', slug: 'os-threads', title: 'OS: Threads', sortOrder: 42, hasCodeFile: true },
  {
    courseKey: 'c',
    slug: 'recap-os',
    title: 'Recap: Parallel Word Counter',
    sortOrder: 43,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'project-student-db',
    title: 'Project: Student Database',
    sortOrder: 44,
    hasCodeFile: true,
  },
  {
    courseKey: 'c',
    slug: 'project-mini-shell',
    title: 'Project: Mini Shell',
    sortOrder: 45,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'print', title: 'Print', sortOrder: 1, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'variables-int',
    title: 'Variables (Numbers)',
    sortOrder: 2,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'variables-str',
    title: 'Variables (Strings)',
    sortOrder: 3,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'concat',
    title: 'String Concatenation',
    sortOrder: 4,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-basics',
    title: 'Recap: Receipt Printer',
    sortOrder: 5,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'comment', title: 'Comments', sortOrder: 6, hasCodeFile: true },
  { courseKey: 'java', slug: 'if-else', title: 'If/Else', sortOrder: 7, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'if-else-if',
    title: 'If/Else If/Else',
    sortOrder: 8,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'for', title: 'For Loops', sortOrder: 9, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'recap-conditionals',
    title: 'Recap: Grade Classifier',
    sortOrder: 10,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'while', title: 'While Loops', sortOrder: 11, hasCodeFile: true },
  { courseKey: 'java', slug: 'methods', title: 'Methods', sortOrder: 12, hasCodeFile: true },
  { courseKey: 'java', slug: 'input', title: 'Input', sortOrder: 13, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'recap-loops',
    title: 'Recap: Number Cruncher',
    sortOrder: 14,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'operators', title: 'Operators', sortOrder: 15, hasCodeFile: true },
  { courseKey: 'java', slug: 'booleans', title: 'Booleans', sortOrder: 16, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'strings-methods',
    title: 'String Methods',
    sortOrder: 17,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'arrays', title: 'Arrays', sortOrder: 18, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'arrays-for',
    title: 'Looping over Arrays',
    sortOrder: 19,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'break-continue',
    title: 'Break and Continue',
    sortOrder: 20,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-arrays',
    title: 'Recap: Word Filter',
    sortOrder: 21,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'return-values',
    title: 'Return Values',
    sortOrder: 22,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'method-overloading',
    title: 'Method Overloading',
    sortOrder: 23,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'nested-loops',
    title: 'Nested Loops',
    sortOrder: 24,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-methods',
    title: 'Recap: Pattern Printer',
    sortOrder: 25,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'arraylist', title: 'ArrayList', sortOrder: 26, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'arraylist-loops',
    title: 'Looping over ArrayLists',
    sortOrder: 27,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'hashmap', title: 'HashMap', sortOrder: 28, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'hashmap-loops',
    title: 'Looping over HashMaps',
    sortOrder: 29,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-collections',
    title: 'Recap: Inventory Tracker',
    sortOrder: 30,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'math-class',
    title: 'The Math Class',
    sortOrder: 31,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'classes-objects',
    title: 'Classes and Objects',
    sortOrder: 32,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'constructors',
    title: 'Constructors',
    sortOrder: 33,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'classes-methods',
    title: 'Methods Inside Classes',
    sortOrder: 34,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-oop-basics',
    title: 'Recap: Pet Shelter',
    sortOrder: 35,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'getters-setters',
    title: 'Getters and Setters',
    sortOrder: 36,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'tostring', title: 'toString()', sortOrder: 37, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'static-keyword',
    title: 'The static Keyword',
    sortOrder: 38,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'final-keyword',
    title: 'The final Keyword',
    sortOrder: 39,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-encapsulation',
    title: 'Recap: Bank Account',
    sortOrder: 40,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'scope-and-access',
    title: 'Scope and Access',
    sortOrder: 41,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'null', title: 'null', sortOrder: 42, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'wrapper-classes',
    title: 'Wrapper Classes',
    sortOrder: 43,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'inheritance',
    title: 'Inheritance',
    sortOrder: 44,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'inheritance-override',
    title: 'Overriding Methods',
    sortOrder: 45,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'polymorphism',
    title: 'Polymorphism',
    sortOrder: 46,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'abstract-classes',
    title: 'Abstract Classes',
    sortOrder: 47,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-inheritance',
    title: 'Recap: Vehicle Fleet',
    sortOrder: 48,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'interfaces', title: 'Interfaces', sortOrder: 49, hasCodeFile: true },
  { courseKey: 'java', slug: 'casting', title: 'Type Casting', sortOrder: 50, hasCodeFile: true },
  { courseKey: 'java', slug: 'exceptions', title: 'Try / Catch', sortOrder: 51, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'string-format',
    title: 'String.format()',
    sortOrder: 52,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-interfaces',
    title: 'Recap: Shape Calculator',
    sortOrder: 53,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'collections-sort',
    title: 'Sorting Collections',
    sortOrder: 54,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'for-each-advanced',
    title: 'Enhanced Patterns',
    sortOrder: 55,
    hasCodeFile: true,
  },
  { courseKey: 'java', slug: 'enums', title: 'Enums', sortOrder: 56, hasCodeFile: true },
  {
    courseKey: 'java',
    slug: 'switch',
    title: 'Switch Statements',
    sortOrder: 57,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'recap-final',
    title: 'Recap: Task Board',
    sortOrder: 58,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'project-inventory',
    title: 'Project: Inventory System',
    sortOrder: 59,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'project-battle',
    title: 'Project: Battle Simulator',
    sortOrder: 60,
    hasCodeFile: true,
  },
  {
    courseKey: 'java',
    slug: 'project-student-grades',
    title: 'Project: Student Gradebook',
    sortOrder: 61,
    hasCodeFile: true,
  },

  {
    courseKey: 'linux',
    slug: 'what-is-terminal',
    title: 'What Is a Terminal?',
    sortOrder: 1,
    hasCodeFile: false,
  },
  { courseKey: 'linux', slug: 'pwd', title: 'pwd — Where Am I?', sortOrder: 2, hasCodeFile: false },
  { courseKey: 'linux', slug: 'ls', title: 'ls — List Files', sortOrder: 3, hasCodeFile: false },
  { courseKey: 'linux', slug: 'ls-options', title: 'ls Options', sortOrder: 4, hasCodeFile: false },
  {
    courseKey: 'linux',
    slug: 'cd',
    title: 'cd — Change Directory',
    sortOrder: 5,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'tree-paths',
    title: 'Tree and Paths',
    sortOrder: 6,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-navigation',
    title: 'Recap: Navigation',
    sortOrder: 7,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'mkdir',
    title: 'mkdir — Create Directories',
    sortOrder: 8,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'touch',
    title: 'touch — Create Files',
    sortOrder: 9,
    hasCodeFile: false,
  },
  { courseKey: 'linux', slug: 'cp', title: 'cp — Copy Files', sortOrder: 10, hasCodeFile: false },
  {
    courseKey: 'linux',
    slug: 'mv',
    title: 'mv — Move and Rename',
    sortOrder: 11,
    hasCodeFile: false,
  },
  { courseKey: 'linux', slug: 'rm', title: 'rm — Remove Files', sortOrder: 12, hasCodeFile: false },
  {
    courseKey: 'linux',
    slug: 'rm-dir',
    title: 'Removing Directories',
    sortOrder: 13,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-files',
    title: 'Recap: File Management',
    sortOrder: 14,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'cat',
    title: 'cat — View File Contents',
    sortOrder: 15,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'cat-options',
    title: 'cat Options',
    sortOrder: 16,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'head',
    title: 'head — First Lines',
    sortOrder: 17,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'tail',
    title: 'tail — Last Lines',
    sortOrder: 18,
    hasCodeFile: false,
  },
  { courseKey: 'linux', slug: 'wc', title: 'wc — Word Count', sortOrder: 19, hasCodeFile: false },
  {
    courseKey: 'linux',
    slug: 'less',
    title: 'less — Page Through Files',
    sortOrder: 20,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-viewing',
    title: 'Recap: Viewing Files',
    sortOrder: 21,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'grep',
    title: 'grep — Search in Files',
    sortOrder: 22,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'grep-options',
    title: 'grep Options',
    sortOrder: 23,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'grep-recursive',
    title: 'grep — Recursive Search',
    sortOrder: 24,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'find',
    title: 'find — Locate Files',
    sortOrder: 25,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'find-filters',
    title: 'find Filters',
    sortOrder: 26,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'which-file',
    title: 'which and file',
    sortOrder: 27,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-search',
    title: 'Recap: Search Tools',
    sortOrder: 28,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'redirect-out',
    title: 'Output to a File — >',
    sortOrder: 29,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'redirect-append',
    title: 'Appending — >>',
    sortOrder: 30,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'redirect-in',
    title: 'Input from a File — <',
    sortOrder: 31,
    hasCodeFile: false,
  },
  { courseKey: 'linux', slug: 'pipe', title: 'The Pipe — |', sortOrder: 32, hasCodeFile: false },
  {
    courseKey: 'linux',
    slug: 'pipelines',
    title: 'Building Pipelines',
    sortOrder: 33,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'stderr',
    title: 'Errors vs Output — 2>',
    sortOrder: 34,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-pipes',
    title: 'Recap: Data Pipeline',
    sortOrder: 35,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'sort',
    title: 'Sorting Lines — sort',
    sortOrder: 36,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'sort-options',
    title: 'Numeric & Key Sorting',
    sortOrder: 37,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'uniq',
    title: 'Unique Lines — uniq',
    sortOrder: 38,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'cut',
    title: 'Cutting Columns — cut',
    sortOrder: 39,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'sed',
    title: 'Find & Replace — sed',
    sortOrder: 40,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'awk',
    title: 'Field Processing — awk',
    sortOrder: 41,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'awk-counting',
    title: 'Counting with awk',
    sortOrder: 42,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-text',
    title: 'Recap: Report Generator',
    sortOrder: 43,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'permissions-intro',
    title: 'Reading Permissions',
    sortOrder: 44,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'chmod-symbolic',
    title: 'chmod — Symbolic Mode',
    sortOrder: 45,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'chmod-numeric',
    title: 'chmod — Numeric Mode',
    sortOrder: 46,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'whoami-id',
    title: 'Ownership & Identity',
    sortOrder: 47,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-permissions',
    title: 'Recap: Lock It Down',
    sortOrder: 48,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'ps',
    title: 'Running Processes — ps',
    sortOrder: 49,
    hasCodeFile: false,
  },
  { courseKey: 'linux', slug: 'top', title: 'Live View — top', sortOrder: 50, hasCodeFile: false },
  {
    courseKey: 'linux',
    slug: 'kill',
    title: 'Stopping Processes — kill',
    sortOrder: 51,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'df-du',
    title: 'Disk & Memory — df & du',
    sortOrder: 52,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'date-history',
    title: 'Date, Uptime & History',
    sortOrder: 53,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'recap-processes',
    title: 'Recap: System Checkup',
    sortOrder: 54,
    hasCodeFile: false,
  },
  {
    courseKey: 'linux',
    slug: 'project-mission-control',
    title: 'Project: Mission Control',
    sortOrder: 55,
    hasCodeFile: false,
  },

  {
    courseKey: 'algo-python',
    slug: 'reverse-string',
    title: 'Easy · Reverse a String',
    sortOrder: 1,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'sum-of-digits',
    title: 'Easy · Sum of Digits',
    sortOrder: 2,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'count-vowels',
    title: 'Easy · Count Vowels',
    sortOrder: 3,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'palindrome',
    title: 'Easy · Palindrome Check',
    sortOrder: 4,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'find-maximum',
    title: 'Easy · Find Maximum',
    sortOrder: 5,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'even-or-odd',
    title: 'Easy · Even or Odd',
    sortOrder: 6,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'count-words',
    title: 'Easy · Count Words',
    sortOrder: 7,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'sum-of-list',
    title: 'Easy · Sum of List',
    sortOrder: 8,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'longest-word',
    title: 'Easy · Longest Word',
    sortOrder: 9,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'reverse-words',
    title: 'Easy · Reverse Words',
    sortOrder: 10,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'words-with-vowels',
    title: 'Medium · Words with Two Vowels',
    sortOrder: 11,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'caesar-cipher',
    title: 'Medium · Caesar Cipher',
    sortOrder: 12,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'remove-duplicates',
    title: 'Medium · Remove Duplicates',
    sortOrder: 13,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'anagram-check',
    title: 'Medium · Anagram Check',
    sortOrder: 14,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'two-sum',
    title: 'Hard · Two Sum',
    sortOrder: 15,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'fizzbuzz',
    title: 'Easy · FizzBuzz',
    sortOrder: 16,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'fibonacci',
    title: 'Medium · Fibonacci',
    sortOrder: 17,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'insertion-sort',
    title: 'Medium · Insertion Sort',
    sortOrder: 18,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'matrix-spiral',
    title: 'Hard · Matrix Spiral',
    sortOrder: 19,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-python',
    slug: 'group-anagrams',
    title: 'Hard · Group Anagrams',
    sortOrder: 20,
    hasCodeFile: true,
  },

  {
    courseKey: 'algo-java',
    slug: 'student-gpa',
    title: 'Easy · Student GPA',
    sortOrder: 1,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'rectangle-calc',
    title: 'Easy · Rectangle Calculator',
    sortOrder: 2,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'bank-account',
    title: 'Easy · Bank Account',
    sortOrder: 3,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'counter-class',
    title: 'Easy · Counter Class',
    sortOrder: 4,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'temperature-converter',
    title: 'Easy · Temperature Converter',
    sortOrder: 5,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'string-stats',
    title: 'Easy · String Stats',
    sortOrder: 6,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'dice-roller',
    title: 'Easy · Dice Roller',
    sortOrder: 7,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'shopping-item',
    title: 'Easy · Shopping Item',
    sortOrder: 8,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'comparable-sort',
    title: 'Medium · Sort Students',
    sortOrder: 9,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'inventory-manager',
    title: 'Medium · Inventory Manager',
    sortOrder: 10,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'shape-hierarchy',
    title: 'Medium · Shape Hierarchy',
    sortOrder: 11,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'stack-impl',
    title: 'Medium · Stack Implementation',
    sortOrder: 12,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'linked-list',
    title: 'Hard · Linked List',
    sortOrder: 13,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'iterator-pattern',
    title: 'Hard · Number Range Iterator',
    sortOrder: 14,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'generic-pair',
    title: 'Hard · Generic Pair',
    sortOrder: 15,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'binary-search',
    title: 'Easy · Binary Search',
    sortOrder: 16,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'bubble-sort',
    title: 'Easy · Bubble Sort',
    sortOrder: 17,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'queue-impl',
    title: 'Medium · Queue Implementation',
    sortOrder: 18,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'palindrome-number',
    title: 'Easy · Palindrome Number',
    sortOrder: 19,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-java',
    slug: 'matrix-multiply',
    title: 'Hard · Matrix Multiplication',
    sortOrder: 20,
    hasCodeFile: true,
  },

  {
    courseKey: 'algo-c',
    slug: 'reverse-array',
    title: 'Easy · Reverse an Array',
    sortOrder: 1,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'string-length',
    title: 'Easy · String Length',
    sortOrder: 2,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'count-chars',
    title: 'Easy · Count Characters',
    sortOrder: 3,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'sum-array',
    title: 'Easy · Sum Array',
    sortOrder: 4,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'find-min',
    title: 'Easy · Find Minimum',
    sortOrder: 5,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'even-count',
    title: 'Easy · Even Count',
    sortOrder: 6,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'print-triangle',
    title: 'Easy · Print Triangle',
    sortOrder: 7,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'digit-count',
    title: 'Easy · Digit Count',
    sortOrder: 8,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'swap-pointers',
    title: 'Medium · Swap with Pointers',
    sortOrder: 9,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'dynamic-array',
    title: 'Medium · Dynamic Array',
    sortOrder: 10,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'matrix-transpose',
    title: 'Medium · Matrix Transpose',
    sortOrder: 11,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'struct-sort',
    title: 'Medium · Sort Students',
    sortOrder: 12,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'bitwise-ops',
    title: 'Hard · Bitwise Power of Two',
    sortOrder: 13,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'linked-list-c',
    title: 'Hard · Linked List',
    sortOrder: 14,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'merge-sort',
    title: 'Hard · Merge Sort',
    sortOrder: 15,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'insertion-sort-c',
    title: 'Medium · Insertion Sort',
    sortOrder: 16,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'binary-search-c',
    title: 'Easy · Binary Search',
    sortOrder: 17,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'stack-array',
    title: 'Medium · Stack with Array',
    sortOrder: 18,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'caesar-cipher-c',
    title: 'Medium · Caesar Cipher',
    sortOrder: 19,
    hasCodeFile: true,
  },
  {
    courseKey: 'algo-c',
    slug: 'gcd-lcm',
    title: 'Easy · GCD & LCM',
    sortOrder: 20,
    hasCodeFile: true,
  },
  {
    courseKey: 'kotlin',
    slug: 'hello-world',
    title: 'Hello World',
    sortOrder: 1,
    hasCodeFile: true,
  },
];
