import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const courses = [
  { key: "python", title: "Python", description: "New to programming? We highly recommend Python", sortOrder: 1 },
  { key: "c", title: "C", description: "Low-level programming, pointers, memory, and OS concepts", sortOrder: 2 },
  { key: "java", title: "Java", description: "Object Oriented Programming", sortOrder: 3 },
  { key: "algo", title: "Algorithms", description: "Practice with classic LeetCode-style problems — strings, sorting, hash maps", sortOrder: 4 },
];

const lessons = [
  { courseKey: "python", slug: "print", title: "Print", sortOrder: 1, hasCodeFile: true },
  { courseKey: "python", slug: "variables-str", title: "Variables (Strings)", sortOrder: 2, hasCodeFile: true },
  { courseKey: "python", slug: "variables-int", title: "Variables (Integers)", sortOrder: 3, hasCodeFile: true },
  { courseKey: "python", slug: "print-f", title: "Print F-strings", sortOrder: 4, hasCodeFile: true },
  { courseKey: "python", slug: "recap-variables", title: "Recap: Player Card", sortOrder: 5, hasCodeFile: true },
  { courseKey: "python", slug: "comment", title: "Comments", sortOrder: 6, hasCodeFile: true },
  { courseKey: "python", slug: "if-else", title: "If/Else", sortOrder: 7, hasCodeFile: true },
  { courseKey: "python", slug: "if-elif-else", title: "If/Elif/Else", sortOrder: 8, hasCodeFile: true },
  { courseKey: "python", slug: "recap-conditionals", title: "Recap: Ticket Calculator", sortOrder: 9, hasCodeFile: true },
  { courseKey: "python", slug: "for", title: "For Loops", sortOrder: 10, hasCodeFile: true },
  { courseKey: "python", slug: "while", title: "While Loops", sortOrder: 11, hasCodeFile: true },
  { courseKey: "python", slug: "functions", title: "Functions", sortOrder: 12, hasCodeFile: true },
  { courseKey: "python", slug: "recap-loops", title: "Recap: Number Hints", sortOrder: 13, hasCodeFile: true },
  { courseKey: "python", slug: "input", title: "Input", sortOrder: 14, hasCodeFile: true },
  { courseKey: "python", slug: "operators", title: "Operators", sortOrder: 15, hasCodeFile: true },
  { courseKey: "python", slug: "booleans", title: "Booleans", sortOrder: 16, hasCodeFile: true },
  { courseKey: "python", slug: "recap-logic", title: "Recap: Username Validator", sortOrder: 17, hasCodeFile: true },
  { courseKey: "python", slug: "strings-methods", title: "String Methods", sortOrder: 18, hasCodeFile: true },
  { courseKey: "python", slug: "lists", title: "Lists", sortOrder: 19, hasCodeFile: true },
  { courseKey: "python", slug: "lists-for", title: "Looping over Lists", sortOrder: 20, hasCodeFile: true },
  { courseKey: "python", slug: "break-continue", title: "Break and Continue", sortOrder: 21, hasCodeFile: true },
  { courseKey: "python", slug: "recap-collections", title: "Recap: Shopping List", sortOrder: 22, hasCodeFile: true },
  { courseKey: "python", slug: "return", title: "Return Values", sortOrder: 23, hasCodeFile: true },
  { courseKey: "python", slug: "dictionaries", title: "Dictionaries", sortOrder: 24, hasCodeFile: true },
  { courseKey: "python", slug: "dictionaries-loop", title: "Looping over Dictionaries", sortOrder: 25, hasCodeFile: true },
  { courseKey: "python", slug: "recap-dicts", title: "Recap: Grade Report", sortOrder: 26, hasCodeFile: true },
  { courseKey: "python", slug: "tuples", title: "Tuples", sortOrder: 27, hasCodeFile: true },
  { courseKey: "python", slug: "sets", title: "Sets", sortOrder: 28, hasCodeFile: true },
  { courseKey: "python", slug: "nested-loops", title: "Nested Loops", sortOrder: 29, hasCodeFile: true },
  { courseKey: "python", slug: "list-comprehension", title: "List Comprehension", sortOrder: 30, hasCodeFile: true },
  { courseKey: "python", slug: "recap-data-structures", title: "Recap: Class Analyzer", sortOrder: 31, hasCodeFile: true },
  { courseKey: "python", slug: "scope", title: "Scope", sortOrder: 32, hasCodeFile: true },
  { courseKey: "python", slug: "default-params", title: "Default Parameters", sortOrder: 33, hasCodeFile: true },
  { courseKey: "python", slug: "multiple-return", title: "Multiple Return Values", sortOrder: 34, hasCodeFile: true },
  { courseKey: "python", slug: "try-except", title: "Try / Except", sortOrder: 35, hasCodeFile: true },
  { courseKey: "python", slug: "recap-functions-adv", title: "Recap: Safe Math Toolkit", sortOrder: 36, hasCodeFile: true },
  { courseKey: "python", slug: "builtin-functions", title: "Built-in Functions", sortOrder: 37, hasCodeFile: true },
  { courseKey: "python", slug: "problem-decomposition", title: "Problem Decomposition", sortOrder: 38, hasCodeFile: true },
  { courseKey: "python", slug: "pattern-counter", title: "Pattern: Counter", sortOrder: 39, hasCodeFile: true },
  { courseKey: "python", slug: "pattern-accumulator", title: "Pattern: Accumulator", sortOrder: 40, hasCodeFile: true },
  { courseKey: "python", slug: "pattern-flag", title: "Pattern: Flag", sortOrder: 41, hasCodeFile: true },
  { courseKey: "python", slug: "recap-patterns", title: "Recap: Text Analyzer", sortOrder: 42, hasCodeFile: true },
  { courseKey: "python", slug: "linear-search", title: "Linear Search", sortOrder: 43, hasCodeFile: true },
  { courseKey: "python", slug: "frequency-dict", title: "Frequency Dictionary", sortOrder: 44, hasCodeFile: true },
  { courseKey: "python", slug: "bubble-sort", title: "Bubble Sort", sortOrder: 45, hasCodeFile: true },
  { courseKey: "python", slug: "selection-sort", title: "Selection Sort", sortOrder: 46, hasCodeFile: true },
  { courseKey: "python", slug: "recap-algorithms", title: "Recap: Leaderboard", sortOrder: 47, hasCodeFile: true },
  { courseKey: "python", slug: "string-reverse", title: "Reverse a String", sortOrder: 48, hasCodeFile: true },
  { courseKey: "python", slug: "palindrome", title: "Palindrome", sortOrder: 49, hasCodeFile: true },
  { courseKey: "python", slug: "anagram", title: "Anagram", sortOrder: 50, hasCodeFile: true },
  { courseKey: "python", slug: "list-filter-transform", title: "Filter and Transform", sortOrder: 51, hasCodeFile: true },
  { courseKey: "python", slug: "two-pointers", title: "Two Pointers", sortOrder: 52, hasCodeFile: true },
  { courseKey: "python", slug: "recap-problem-solving", title: "Recap: Word Game Toolkit", sortOrder: 53, hasCodeFile: true },
  { courseKey: "python", slug: "recursion-intro", title: "Recursion", sortOrder: 54, hasCodeFile: true },
  { courseKey: "python", slug: "recursion-practice", title: "Recursion Practice", sortOrder: 55, hasCodeFile: true },
  { courseKey: "python", slug: "matrix-basics", title: "Matrices (2D Lists)", sortOrder: 56, hasCodeFile: true },
  { courseKey: "python", slug: "binary-search", title: "Binary Search", sortOrder: 57, hasCodeFile: true },
  { courseKey: "python", slug: "recap-recursion", title: "Recap: Dungeon Explorer", sortOrder: 58, hasCodeFile: true },
  { courseKey: "python", slug: "project-guessing-game", title: "Project: Guessing Game", sortOrder: 59, hasCodeFile: true },
  { courseKey: "python", slug: "project-quiz", title: "Project: Quiz Game", sortOrder: 60, hasCodeFile: true },
  { courseKey: "python", slug: "project-todo", title: "Project: To-Do List", sortOrder: 61, hasCodeFile: true },
  { courseKey: "c", slug: "print", title: "Print", sortOrder: 1, hasCodeFile: true },
  { courseKey: "c", slug: "variables-int", title: "Variables (Integers)", sortOrder: 2, hasCodeFile: true },
  { courseKey: "c", slug: "variables-float", title: "Variables (Floats)", sortOrder: 3, hasCodeFile: true },
  { courseKey: "c", slug: "comment", title: "Comments", sortOrder: 4, hasCodeFile: true },
  { courseKey: "c", slug: "recap-variables", title: "Recap: Road Trip Calculator", sortOrder: 5, hasCodeFile: true },
  { courseKey: "c", slug: "if-else", title: "If/Else", sortOrder: 6, hasCodeFile: true },
  { courseKey: "c", slug: "if-else-if", title: "If/Else If/Else", sortOrder: 7, hasCodeFile: true },
  { courseKey: "c", slug: "for", title: "For Loops", sortOrder: 8, hasCodeFile: true },
  { courseKey: "c", slug: "recap-control-flow", title: "Recap: FizzBuzz", sortOrder: 9, hasCodeFile: true },
  { courseKey: "c", slug: "while", title: "While Loops", sortOrder: 10, hasCodeFile: true },
  { courseKey: "c", slug: "functions", title: "Functions", sortOrder: 11, hasCodeFile: true },
  { courseKey: "c", slug: "input", title: "Input", sortOrder: 12, hasCodeFile: true },
  { courseKey: "c", slug: "recap-functions", title: "Recap: Mini Calculator", sortOrder: 13, hasCodeFile: true },
  { courseKey: "c", slug: "operators", title: "Operators", sortOrder: 14, hasCodeFile: true },
  { courseKey: "c", slug: "booleans", title: "Booleans", sortOrder: 15, hasCodeFile: true },
  { courseKey: "c", slug: "strings", title: "Strings", sortOrder: 16, hasCodeFile: true },
  { courseKey: "c", slug: "recap-logic", title: "Recap: Password Validator", sortOrder: 17, hasCodeFile: true },
  { courseKey: "c", slug: "arrays", title: "Arrays", sortOrder: 18, hasCodeFile: true },
  { courseKey: "c", slug: "arrays-for", title: "Looping over Arrays", sortOrder: 19, hasCodeFile: true },
  { courseKey: "c", slug: "break-continue", title: "Break and Continue", sortOrder: 20, hasCodeFile: true },
  { courseKey: "c", slug: "recap-arrays", title: "Recap: Grade Analyzer", sortOrder: 21, hasCodeFile: true },
  { courseKey: "c", slug: "nested-loops", title: "Nested Loops", sortOrder: 22, hasCodeFile: true },
  { courseKey: "c", slug: "pointers", title: "Pointers", sortOrder: 23, hasCodeFile: true },
  { courseKey: "c", slug: "pointers-functions", title: "Pointers and Functions", sortOrder: 24, hasCodeFile: true },
  { courseKey: "c", slug: "recap-pointers", title: "Recap: Matrix Stats", sortOrder: 25, hasCodeFile: true },
  { courseKey: "c", slug: "pointers-arrays", title: "Pointers and Arrays", sortOrder: 26, hasCodeFile: true },
  { courseKey: "c", slug: "strings-functions", title: "String Functions", sortOrder: 27, hasCodeFile: true },
  { courseKey: "c", slug: "structs", title: "Structs", sortOrder: 28, hasCodeFile: true },
  { courseKey: "c", slug: "structs-pointers", title: "Structs and Pointers", sortOrder: 29, hasCodeFile: true },
  { courseKey: "c", slug: "recap-structs", title: "Recap: Contact Book", sortOrder: 30, hasCodeFile: true },
  { courseKey: "c", slug: "malloc-free", title: "Dynamic Memory", sortOrder: 31, hasCodeFile: true },
  { courseKey: "c", slug: "enums", title: "Enums", sortOrder: 32, hasCodeFile: true },
  { courseKey: "c", slug: "typedef", title: "Typedef", sortOrder: 33, hasCodeFile: true },
  { courseKey: "c", slug: "recap-memory", title: "Recap: Task Manager", sortOrder: 34, hasCodeFile: true },
  { courseKey: "c", slug: "preprocessor", title: "Preprocessor", sortOrder: 35, hasCodeFile: true },
  { courseKey: "c", slug: "file-io", title: "File I/O", sortOrder: 36, hasCodeFile: true },
  { courseKey: "c", slug: "bitwise", title: "Bitwise Operators", sortOrder: 37, hasCodeFile: true },
  { courseKey: "c", slug: "recap-advanced", title: "Recap: Config & Permissions", sortOrder: 38, hasCodeFile: true },
  { courseKey: "c", slug: "os-intro", title: "OS: Processes", sortOrder: 39, hasCodeFile: true },
  { courseKey: "c", slug: "os-fork", title: "OS: Fork", sortOrder: 40, hasCodeFile: true },
  { courseKey: "c", slug: "os-pipes", title: "OS: Pipes", sortOrder: 41, hasCodeFile: true },
  { courseKey: "c", slug: "os-threads", title: "OS: Threads", sortOrder: 42, hasCodeFile: true },
  { courseKey: "c", slug: "recap-os", title: "Recap: Parallel Word Counter", sortOrder: 43, hasCodeFile: true },
  { courseKey: "c", slug: "project-student-db", title: "Project: Student Database", sortOrder: 44, hasCodeFile: true },
  { courseKey: "c", slug: "project-mini-shell", title: "Project: Mini Shell", sortOrder: 45, hasCodeFile: true },
  { courseKey: "java", slug: "print", title: "Print", sortOrder: 1, hasCodeFile: true },
  { courseKey: "java", slug: "variables-int", title: "Variables (Numbers)", sortOrder: 2, hasCodeFile: true },
  { courseKey: "java", slug: "variables-str", title: "Variables (Strings)", sortOrder: 3, hasCodeFile: true },
  { courseKey: "java", slug: "concat", title: "String Concatenation", sortOrder: 4, hasCodeFile: true },
  { courseKey: "java", slug: "recap-basics", title: "Recap: Receipt Printer", sortOrder: 5, hasCodeFile: true },
  { courseKey: "java", slug: "comment", title: "Comments", sortOrder: 6, hasCodeFile: true },
  { courseKey: "java", slug: "if-else", title: "If/Else", sortOrder: 7, hasCodeFile: true },
  { courseKey: "java", slug: "if-else-if", title: "If/Else If/Else", sortOrder: 8, hasCodeFile: true },
  { courseKey: "java", slug: "for", title: "For Loops", sortOrder: 9, hasCodeFile: true },
  { courseKey: "java", slug: "recap-conditionals", title: "Recap: Grade Classifier", sortOrder: 10, hasCodeFile: true },
  { courseKey: "java", slug: "while", title: "While Loops", sortOrder: 11, hasCodeFile: true },
  { courseKey: "java", slug: "methods", title: "Methods", sortOrder: 12, hasCodeFile: true },
  { courseKey: "java", slug: "input", title: "Input", sortOrder: 13, hasCodeFile: true },
  { courseKey: "java", slug: "recap-loops", title: "Recap: Number Cruncher", sortOrder: 14, hasCodeFile: true },
  { courseKey: "java", slug: "operators", title: "Operators", sortOrder: 15, hasCodeFile: true },
  { courseKey: "java", slug: "booleans", title: "Booleans", sortOrder: 16, hasCodeFile: true },
  { courseKey: "java", slug: "strings-methods", title: "String Methods", sortOrder: 17, hasCodeFile: true },
  { courseKey: "java", slug: "arrays", title: "Arrays", sortOrder: 18, hasCodeFile: true },
  { courseKey: "java", slug: "arrays-for", title: "Looping over Arrays", sortOrder: 19, hasCodeFile: true },
  { courseKey: "java", slug: "break-continue", title: "Break and Continue", sortOrder: 20, hasCodeFile: true },
  { courseKey: "java", slug: "recap-arrays", title: "Recap: Word Filter", sortOrder: 21, hasCodeFile: true },
  { courseKey: "java", slug: "return-values", title: "Return Values", sortOrder: 22, hasCodeFile: true },
  { courseKey: "java", slug: "method-overloading", title: "Method Overloading", sortOrder: 23, hasCodeFile: true },
  { courseKey: "java", slug: "nested-loops", title: "Nested Loops", sortOrder: 24, hasCodeFile: true },
  { courseKey: "java", slug: "recap-methods", title: "Recap: Pattern Printer", sortOrder: 25, hasCodeFile: true },
  { courseKey: "java", slug: "arraylist", title: "ArrayList", sortOrder: 26, hasCodeFile: true },
  { courseKey: "java", slug: "arraylist-loops", title: "Looping over ArrayLists", sortOrder: 27, hasCodeFile: true },
  { courseKey: "java", slug: "hashmap", title: "HashMap", sortOrder: 28, hasCodeFile: true },
  { courseKey: "java", slug: "hashmap-loops", title: "Looping over HashMaps", sortOrder: 29, hasCodeFile: true },
  { courseKey: "java", slug: "recap-collections", title: "Recap: Inventory Tracker", sortOrder: 30, hasCodeFile: true },
  { courseKey: "java", slug: "math-class", title: "The Math Class", sortOrder: 31, hasCodeFile: true },
  { courseKey: "java", slug: "classes-objects", title: "Classes and Objects", sortOrder: 32, hasCodeFile: true },
  { courseKey: "java", slug: "constructors", title: "Constructors", sortOrder: 33, hasCodeFile: true },
  { courseKey: "java", slug: "classes-methods", title: "Methods Inside Classes", sortOrder: 34, hasCodeFile: true },
  { courseKey: "java", slug: "recap-oop-basics", title: "Recap: Pet Shelter", sortOrder: 35, hasCodeFile: true },
  { courseKey: "java", slug: "getters-setters", title: "Getters and Setters", sortOrder: 36, hasCodeFile: true },
  { courseKey: "java", slug: "tostring", title: "toString()", sortOrder: 37, hasCodeFile: true },
  { courseKey: "java", slug: "static-keyword", title: "The static Keyword", sortOrder: 38, hasCodeFile: true },
  { courseKey: "java", slug: "final-keyword", title: "The final Keyword", sortOrder: 39, hasCodeFile: true },
  { courseKey: "java", slug: "recap-encapsulation", title: "Recap: Bank Account", sortOrder: 40, hasCodeFile: true },
  { courseKey: "java", slug: "scope-and-access", title: "Scope and Access", sortOrder: 41, hasCodeFile: true },
  { courseKey: "java", slug: "null", title: "null", sortOrder: 42, hasCodeFile: true },
  { courseKey: "java", slug: "wrapper-classes", title: "Wrapper Classes", sortOrder: 43, hasCodeFile: true },
  { courseKey: "java", slug: "inheritance", title: "Inheritance", sortOrder: 44, hasCodeFile: true },
  { courseKey: "java", slug: "inheritance-override", title: "Overriding Methods", sortOrder: 45, hasCodeFile: true },
  { courseKey: "java", slug: "polymorphism", title: "Polymorphism", sortOrder: 46, hasCodeFile: true },
  { courseKey: "java", slug: "abstract-classes", title: "Abstract Classes", sortOrder: 47, hasCodeFile: true },
  { courseKey: "java", slug: "recap-inheritance", title: "Recap: Vehicle Fleet", sortOrder: 48, hasCodeFile: true },
  { courseKey: "java", slug: "interfaces", title: "Interfaces", sortOrder: 49, hasCodeFile: true },
  { courseKey: "java", slug: "casting", title: "Type Casting", sortOrder: 50, hasCodeFile: true },
  { courseKey: "java", slug: "exceptions", title: "Try / Catch", sortOrder: 51, hasCodeFile: true },
  { courseKey: "java", slug: "string-format", title: "String.format()", sortOrder: 52, hasCodeFile: true },
  { courseKey: "java", slug: "recap-interfaces", title: "Recap: Shape Calculator", sortOrder: 53, hasCodeFile: true },
  { courseKey: "java", slug: "collections-sort", title: "Sorting Collections", sortOrder: 54, hasCodeFile: true },
  { courseKey: "java", slug: "for-each-advanced", title: "Enhanced Patterns", sortOrder: 55, hasCodeFile: true },
  { courseKey: "java", slug: "enums", title: "Enums", sortOrder: 56, hasCodeFile: true },
  { courseKey: "java", slug: "switch", title: "Switch Statements", sortOrder: 57, hasCodeFile: true },
  { courseKey: "java", slug: "recap-final", title: "Recap: Task Board", sortOrder: 58, hasCodeFile: true },
  { courseKey: "java", slug: "project-inventory", title: "Project: Inventory System", sortOrder: 59, hasCodeFile: true },
  { courseKey: "java", slug: "project-battle", title: "Project: Battle Simulator", sortOrder: 60, hasCodeFile: true },
  { courseKey: "java", slug: "project-student-grades", title: "Project: Student Gradebook", sortOrder: 61, hasCodeFile: true },

  { courseKey: "algo", slug: "reverse-string", title: "Easy · Reverse a String", sortOrder: 1, hasCodeFile: true },
  { courseKey: "algo", slug: "sum-of-digits", title: "Easy · Sum of Digits", sortOrder: 2, hasCodeFile: true },
  { courseKey: "algo", slug: "count-vowels", title: "Medium · Count Vowels", sortOrder: 3, hasCodeFile: true },
  { courseKey: "algo", slug: "bubble-sort", title: "Medium · Sort the Numbers", sortOrder: 4, hasCodeFile: true },
  { courseKey: "algo", slug: "two-sum", title: "Hard · Two Sum", sortOrder: 5, hasCodeFile: true },
  { courseKey: "algo", slug: "anagram", title: "Hard · Anagram Check", sortOrder: 6, hasCodeFile: true },
];

async function main() {
  for (const course of courses) {
    await prisma.curriculum.upsert({
      where: { key: course.key },
      create: course,
      update: {},
    });
  }

  for (const lesson of lessons) {
    await prisma.lesson.upsert({
      where: { courseKey_slug: { courseKey: lesson.courseKey, slug: lesson.slug } },
      create: lesson,
      update: {},
    });
  }

  console.log(`Seeded ${courses.length} courses and ${lessons.length} lessons.`);
}

main()
  .catch(err => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
